# Generated by Django 5.1.7 on 2025-03-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sVentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
